export ZSH=$HOME/.oh-my-zsh

# zsh configuration
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_THEME=""

# directory vars
if [[ "$REMOTE_DEV_ENV" == "true" ]]; then
  DIR_DEV="$HOME/dev"
  DIR_DOTFILES="$DIR_DEV/dotfiles"
  DIR_DOTFILES_PRIVATE="$HOME/dotfiles"
else
  DIR_DEV="$HOME/dev"
  DIR_DOTFILES="$DIR_DEV/dotfiles"
  DIR_DOTFILES_PRIVATE="$DIR_DEV/dotfiles-private"
fi

# User configuration
export LANG=en_US.UTF-8
# export SSH_KEY_PATH="~/.ssh/id_ed25519" # TODO: check if this is needed
export EDITOR=vim

# Load OS-specific configurations
if [[ "$OSTYPE" == "darwin"* ]]; then
  export UPDATE_ZSH_DAYS=10
  source "$DIR_DOTFILES/zsh/zshrc.macos.sh"
else
  source "$DIR_DOTFILES/zsh/zshrc.linux.sh"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Load Oh My Zsh and plugins
plugins=(git zsh-syntax-highlighting z)
source $ZSH/oh-my-zsh.sh

# Load additional configuration files
source "$DIR_DOTFILES/zsh/alias.sh"
source "$DIR_DOTFILES/zsh/prompt.sh"
source "$DIR_DOTFILES/zsh/shell-functions.sh"

# Load private configurations if they exist
[ -f "$HOME/.iterm2_shell_integration.zsh" ] && source ~/.iterm2_shell_integration.zsh
[ -f "$DIR_DOTFILES_PRIVATE/entry.sh" ] && source "$DIR_DOTFILES_PRIVATE/entry.sh" || false

# bun completions
[ -s "/Users/amohanty/.bun/_bun" ] && source "/Users/amohanty/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Cleanup
unset DIR_DEV DIR_DOTFILES DIR_DOTFILES_PRIVATE

export HEY_IS_THIS_TERE="YEP"
