#!/usr/bin/env bash

# Git configuration setup.
# Keeps mutable global Git state in a tracked file in the dotfiles repository
# so automated changes remain visible for review.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$SCRIPT_DIR/../utils/logging.sh"
source "$SCRIPT_DIR/../utils/file-operations.sh"
source "$SCRIPT_DIR/../utils/environment.sh"
source "$SCRIPT_DIR/../utils/user-config.sh"

CONFIG_DIR="$DOTFILES_ROOT/configs/git"
BASE_GITCONFIG="$CONFIG_DIR/base.gitconfig"
GLOBAL_GITIGNORE="$CONFIG_DIR/global.gitignore"
LOCAL_GITCONFIG="$CONFIG_DIR/local.gitconfig"
LOCAL_USER_GITCONFIG="$CONFIG_DIR/user.gitconfig"
LOCAL_PRIVATE_GITCONFIG="$CONFIG_DIR/private.gitconfig"

# Explicit environment values take precedence over committed profile and local
# overrides, including explicit empty values that disable an optional include.
USER_GITCONFIG_FROM_ENV="${DOTFILES_USER_GITCONFIG-}"
USER_GITCONFIG_FROM_ENV_SET="${DOTFILES_USER_GITCONFIG+x}"
PRIVATE_GITCONFIG_FROM_ENV="${DOTFILES_PRIVATE_GITCONFIG-}"
PRIVATE_GITCONFIG_FROM_ENV_SET="${DOTFILES_PRIVATE_GITCONFIG+x}"
if ! load-user-config; then
  log-error "Unable to load a committed user profile"
  exit 1
fi
if [[ "$USER_GITCONFIG_FROM_ENV_SET" == "x" ]]; then
  DOTFILES_USER_GITCONFIG="$USER_GITCONFIG_FROM_ENV"
fi
if [[ "$PRIVATE_GITCONFIG_FROM_ENV_SET" == "x" ]]; then
  DOTFILES_PRIVATE_GITCONFIG="$PRIVATE_GITCONFIG_FROM_ENV"
fi

setup-git-config() {
  log-info "Setting up git configuration..."

  setup-global-gitignore || return 1

  if is-devbox; then
    create-devbox-gitconfig || return 1
  else
    create-local-gitconfig || return 1
  fi

  warn-about-backup-files
  log-success "Git configuration setup complete"
}

setup-global-gitignore() {
  log-info "Setting up global gitignore..."

  if [[ -e ~/.gitignore || -L ~/.gitignore ]]; then
    if [[ ~/.gitignore -ef "$GLOBAL_GITIGNORE" ]]; then
      log-info "Global gitignore already uses the tracked configuration"
      return 0
    fi
    backup-file ~/.gitignore || return 1
  fi

  ln -sf "$GLOBAL_GITIGNORE" ~/.gitignore || {
    log-error "Failed to create global gitignore symlink"
    return 1
  }
  log-info "Created symlink: ~/.gitignore -> $GLOBAL_GITIGNORE"
}

create-devbox-gitconfig() {
  log-info "Setting up devbox gitconfig..."

  if [[ -f ~/.gitconfig ]] && grep -q "path = $BASE_GITCONFIG" ~/.gitconfig; then
    log-info "Base gitconfig include already exists, skipping"
    return 0
  fi

  {
    if [[ -f ~/.gitconfig ]]; then
      echo ""
      echo "# Base gitconfig include - added by dotfiles setup"
    else
      echo "# Git Configuration for Devbox Environment"
      echo "# Generated by dotfiles setup script"
    fi
    echo "[include]"
    echo "    path = $BASE_GITCONFIG"
  } >> ~/.gitconfig

  log-info "Added base gitconfig include to ~/.gitconfig"
}

create-local-gitconfig() {
  log-info "Setting up local gitconfig..."

  configure-optional-gitconfig "$DOTFILES_USER_GITCONFIG" "$LOCAL_USER_GITCONFIG" "user" || return 1
  configure-optional-gitconfig "$DOTFILES_PRIVATE_GITCONFIG" "$LOCAL_PRIVATE_GITCONFIG" "private" || return 1

  if [[ ! -f "$LOCAL_GITCONFIG" ]]; then
    write-local-gitconfig
    log-info "Created mutable gitconfig: $LOCAL_GITCONFIG"
  else
    update-local-gitconfig-includes
  fi

  if [[ -e ~/.gitconfig || -L ~/.gitconfig ]]; then
    if [[ ~/.gitconfig -ef "$LOCAL_GITCONFIG" ]]; then
      log-info "Global gitconfig already uses the mutable repository config"
    else
      backup-file ~/.gitconfig || return 1
    fi
  fi

  ln -sfn "$LOCAL_GITCONFIG" ~/.gitconfig || {
    log-error "Failed to create global gitconfig symlink"
    return 1
  }
  log-success "Created symlink: ~/.gitconfig -> $LOCAL_GITCONFIG"
  log-info "Tracked include: base.gitconfig"
}

write-local-gitconfig() {
  cat > "$LOCAL_GITCONFIG" <<EOF
# Mutable Git configuration managed by dotfiles setup.
# Tool-managed global state belongs in this tracked repository file.
[include]
    path = $BASE_GITCONFIG

[include]
    path = $LOCAL_PRIVATE_GITCONFIG

[includeIf "gitdir:~/dev/personal/"]
    path = $LOCAL_USER_GITCONFIG

[includeIf "gitdir:~/dev/dotfiles/"]
    path = $LOCAL_USER_GITCONFIG

[includeIf "gitdir:~/dev/dotfiles-private/"]
    path = $LOCAL_USER_GITCONFIG
EOF
}

update-local-gitconfig-includes() {
  # Replace only setup-managed include entries. This preserves tool-managed
  # settings such as [afm] and [trace2] in the tracked local wrapper.
  git config --file "$LOCAL_GITCONFIG" --unset-all include.path || true
  git config --file "$LOCAL_GITCONFIG" --add include.path "$BASE_GITCONFIG"
  git config --file "$LOCAL_GITCONFIG" --add include.path "$LOCAL_PRIVATE_GITCONFIG"
  git config --file "$LOCAL_GITCONFIG" --replace-all 'includeIf.gitdir:~/dev/personal/.path' "$LOCAL_USER_GITCONFIG"
  git config --file "$LOCAL_GITCONFIG" --replace-all 'includeIf.gitdir:~/dev/dotfiles/.path' "$LOCAL_USER_GITCONFIG"
  git config --file "$LOCAL_GITCONFIG" --replace-all 'includeIf.gitdir:~/dev/dotfiles-private/.path' "$LOCAL_USER_GITCONFIG"
}

configure-optional-gitconfig() {
  local configured_path="$1"
  local local_path="$2"
  local config_type="$3"

  rm -f "$local_path"

  if [[ -z "$configured_path" ]]; then
    : > "$local_path"
    log-info "No $config_type gitconfig configured"
    return 0
  fi

  if [[ ! -f "$configured_path" ]]; then
    : > "$local_path"
    log-warning "Optional $config_type gitconfig is unavailable: $configured_path"
    log-warning "Continuing without a $config_type gitconfig include"
    return 0
  fi

  ln -s "$configured_path" "$local_path" || {
    log-error "Failed to configure $config_type gitconfig include"
    return 1
  }
  log-info "Configured $config_type gitconfig include"
}

warn-about-backup-files() {
  local backup_files
  backup_files=$(find "$HOME" -maxdepth 1 -name "*.gitconfig.*" -type f 2>/dev/null)

  if [[ -n "$backup_files" ]]; then
    log-warning "Found leftover backup files from previous setup:"
    echo "$backup_files" | while read -r file; do
      log-warning "  - $(basename "$file")"
    done
    log-warning "You may want to review and remove these files if they're no longer needed"
  fi
}

setup-git-config
