#!/usr/bin/env bash

# Git Configuration Setup Script
# Creates main gitconfig file with base configuration and environment-specific includes

# Source utility functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../utils/logging.sh"
source "$SCRIPT_DIR/../utils/file-operations.sh"

# Source platform detection
source "$SCRIPT_DIR/../../common/utils/platform-detection.sh"

# Configuration directory
DOTFILES_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_DIR="$DOTFILES_ROOT/configs/git"

# Configuration paths
PRIVATE_GITCONFIG="$HOME/dev/dotfiles-private/atlassian/git/amohanty.local.gitconfig"
BASE_GITCONFIG="$CONFIG_DIR/base.gitconfig"
RHEADITI_GITCONFIG="$CONFIG_DIR/rheaditi.gitconfig"
GLOBAL_GITIGNORE="$CONFIG_DIR/global.gitignore"
LOCAL_GITCONFIG="$CONFIG_DIR/local.gitconfig"

# Set up git configuration
setup-git-config() {
  log-info "Setting up git configuration..."

  setup-global-gitignore

  if is-devbox; then
    create-devbox-gitconfig
  else
    create-local-gitconfig
  fi

  warn-about-backup-files
  log-success "Git configuration setup complete"
}

# Set up global gitignore
setup-global-gitignore() {
  log-info "Setting up global gitignore..."

  # Backup existing global gitignore if it exists
  if [[ -f ~/.gitignore ]]; then
    backup-file ~/.gitignore
  fi

  # Create symlink to global gitignore
  ln -sf "$GLOBAL_GITIGNORE" ~/.gitignore
  log-info "Created symlink: ~/.gitignore -> $GLOBAL_GITIGNORE"
}

# Create gitconfig for devbox environment
create-devbox-gitconfig() {
  log-info "Setting up devbox gitconfig..."

  # Check if base.gitconfig include already exists
  if [[ -f ~/.gitconfig ]] && grep -q "path = $BASE_GITCONFIG" ~/.gitconfig; then
    log-info "Base gitconfig include already exists, skipping"
    return 0
  fi

  # Add include to existing file or create new one
  {
    if [[ -f ~/.gitconfig ]]; then
      echo ""
      echo "# Base gitconfig include - added by dotfiles setup"
    else
      echo "# Git Configuration for Devbox Environment"
      echo "# Generated by dotfiles setup script"
    fi
    echo "[include]"
    echo "    path = $BASE_GITCONFIG"
  } >> ~/.gitconfig

  log-info "Added base gitconfig include to ~/.gitconfig"
}

# Create gitconfig for local environment
create-local-gitconfig() {
  log-info "Setting up local gitconfig..."

  # Check if private gitconfig exists
  if [[ ! -f "$PRIVATE_GITCONFIG" ]]; then
    log-error "Required private gitconfig not found: $PRIVATE_GITCONFIG"
    log-error "Please ensure dotfiles-private repository is available"
    return 1
  fi

  # Check if local.gitconfig file exists
  if [[ ! -f "$LOCAL_GITCONFIG" ]]; then
    log-error "Required local gitconfig not found: $LOCAL_GITCONFIG"
    log-error "Please ensure the local.gitconfig file exists in the git directory"
    return 1
  fi

  # Backup existing gitconfig if it exists
  if [[ -f ~/.gitconfig ]]; then
    backup-file ~/.gitconfig
  fi

  # Create symlink to local gitconfig
  ln -sf "$LOCAL_GITCONFIG" ~/.gitconfig
  log-success "Created symlink: ~/.gitconfig -> $LOCAL_GITCONFIG"
  log-info "Includes: base.gitconfig, private config"
  log-info "Conditional includes: rheaditi.gitconfig for ~/dev/personal/ and ~/dev/dotfiles/"
}

# Warn about leftover backup files
warn-about-backup-files() {
  local backup_files
  backup_files=$(find "$HOME" -maxdepth 1 -name "*.gitconfig.*" -type f 2>/dev/null)

  if [[ -n "$backup_files" ]]; then
    log-warning "Found leftover backup files from previous setup:"
    echo "$backup_files" | while read -r file; do
      log-warning "  - $(basename "$file")"
    done
    log-warning "You may want to review and remove these files if they're no longer needed"
  fi
}

# Main execution
setup-git-config
