# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/aditi/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=2

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
export LANG=en_US.UTF-8
# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

## Prompt String Stuff
autoload -U promptinit; promptinit
prompt pure

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
# Generic
alias dev='cd ~/dev'
alias dotfiles='cd ~/dotfiles'
alias moo='fortune | cowsay | lolcat'

# Git things
alias delete-branches='git branch >/tmp/merged-branches && vi /tmp/merged-branches && xargs git branch -D </tmp/merged-branches'
alias clean-merged-branches='git branch --merged >/tmp/merged-branches && vi /tmp/merged-branches && xargs git branch -d </tmp/merged-branches'
alias clean-remote-branches='git branch -a >/tmp/remote-branches && vi /tmp/merged-branches && xargs git branch -d </tmp/merged-branches'
alias reflog='gitk --all --date-order $(git log -g --pretty=%H)'
alias find-dangling='git fsck | grep "dangling commit" | awk "{print $3;}"'

# ClearTax specific
alias fe='cd ~/dev/cleartax-frontend'
alias static='cd ~/dev/cleartax-static-pages'
alias biz='cd ~/dev/cleartax-business'
alias sharedfe='cd ~/dev/cleartax-shared-fe'
alias save='cd ~/dev/clearsave-frontend'
alias taxcloud='cd /Volumes/Transcend/repos/taxcloud-dev'
alias ctax='cd /Volumes/Transcend/repos/cleartax-dev'
alias ctui='cd ~/dev/ct-ui-components'
alias mp='cd ~/dev/mp'
alias mpf='cd ~/dev/mp/ct-marketplace-website'
alias mpc='cd ~/dev/mp/ct-marketplace-cms'
alias mpat='cd ~/dev/mp/ct-marketplace-agent-tools'
alias mppf='cd ~/dev/mp/ct-profile-website'
alias devt='cd /Volumes/Transcend/repos'
alias mine='cd ~/dev/rheaditi.github.io'

# Typo
alias got='git'
alias tit='git'
alias hit='git'
alias hot='git'
alias aton='atom'

# Other Convenience Things :P
alias pra='pm2 restart all'
alias pka='pm2 kill all'
alias pda='pm2 delete all'
alias pmlog='pm2 logs --lines 200'

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
moo # moooooooooooo

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export WORKON_HOME=~/Envs
source /usr/local/bin/virtualenvwrapper.sh
