export ZSH=$HOME/.oh-my-zsh
export UPDATE_ZSH_DAYS=10

# zsh stuff
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_THEME=""

plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh


# User configuration
export LANG=en_US.UTF-8
export SSH_KEY_PATH="~/.ssh/rsa_id"

DIR_DEV="$HOME/dev"
DIR_DOTFILES="$DIR_DEV/dotfiles"

# source remaining files
source "$DIR_DOTFILES/zsh/alias.sh" # this needs to be the first
source "$DIR_DOTFILES/zsh/prompt.sh"
source "$DIR_DOTFILES/zsh/play.sh" # all play 🎮⛏
source "$DIR_DOTFILES/zsh/shell-functions.sh"
[ -f "$DIR_DOTFILES/private/work.sh" ] && source "$DIR_DOTFILES/private/work.sh" || false

# other exports
export EDITOR=vim # use vim for git

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/usr/local/opt/ruby/bin:/$HOME/.gem/ruby/2.6.0/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# deno
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
