#!/usr/bin/env bash
# Sourced by setup.sh — logging, env, and vars are already available.

log_info "Setting up git..."

GITCONFIG="$DIR_HOME/.gitconfig"

# ── Step 1: generate local.gitconfig or devbox.gitconfig ─────────────────────

if is_devbox; then
  GENERATED_GITCONFIG="$DIR_HOME/devbox.gitconfig"
  cat > "$GENERATED_GITCONFIG" << EOF
# Generated by setup.git.sh — do not edit by hand.

[include]
	path = $DIR_DOTFILES/configs/git/base.gitconfig
EOF
  log_success "Generated $GENERATED_GITCONFIG"
else
  GENERATED_GITCONFIG="$DIR_HOME/local.gitconfig"
  cat > "$GENERATED_GITCONFIG" << EOF
# Generated by setup.git.sh — do not edit by hand.

[include]
	path = $DIR_DOTFILES/configs/git/base.gitconfig

[include]
	path = $DIR_DOTFILES_PRIVATE/atlassian/git/amohanty.local.gitconfig

[includeIf "gitdir:$DIR_DEV/personal/"]
	path = $DIR_DOTFILES/configs/git/rheaditi.gitconfig

[includeIf "gitdir:$DIR_DOTFILES/"]
	path = $DIR_DOTFILES/configs/git/rheaditi.gitconfig
EOF
  log_success "Generated $GENERATED_GITCONFIG"
fi

# ── Step 2: ensure ~/.gitconfig exists ───────────────────────────────────────

if [ ! -f "$GITCONFIG" ]; then
  touch "$GITCONFIG"
  log_info "Created empty $GITCONFIG"
fi

# ── Step 3: append include to ~/.gitconfig if not already present ─────────────

if grep -qF "$GENERATED_GITCONFIG" "$GITCONFIG"; then
  log_info "Include already present in $GITCONFIG — skipping"
else
  cat >> "$GITCONFIG" << EOF

[include]
	path = $GENERATED_GITCONFIG
EOF
  log_success "Appended include to $GITCONFIG"
fi

log_success "Git setup complete."
